#!/usr/bin/env python3
"""
Generate rehlds/engine/steam_stub_64.cpp -- a link-time stub for the Steamworks API.

WHY THIS EXISTS
---------------
The bundled lib/linux32/libsteam_api.so is 32-bit only, so a 64-bit engine cannot link.
The 64-bit libsteam_api.so shipped with a modern Steam client is NOT a drop-in replacement:
it implements SteamGameServer015, while ReHLDS's vendored headers
(public/steam/isteamgameserver.h:258) are pinned to SteamGameServer011. Those vtables differ,
so using it would corrupt silently rather than fail to link.

This generates stub implementations of the interfaces the engine references, so a 64-bit
build links and runs in -insecure / LAN mode. It provides NO authentication, NO VAC and NO
master-server listing, and is strictly a development artifact for portability work -- which
is exactly the mitigation the project brief's risk register prescribes ("isolate Steam behind
a compatibility layer; maintain insecure/LAN test mode for core development").

Generating rather than hand-writing keeps the stub honest: the vtable is derived from the
same headers the engine compiles against, so it cannot silently drift out of layout.

Usage:  python3 docs/audit/tools/gen_steam_stub.py > rehlds/engine/steam_stub_64.cpp
"""

import re
import sys
import os
import subprocess

INTERFACES = ["ISteamGameServer", "ISteamUser", "ISteamApps", "ISteamFriends"]

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
STEAM_DIR = os.path.join(REPO, "rehlds", "public", "steam")

# A pure virtual, capturing return type, name and parameter list. Applied to *preprocessed*
# input, so declarations are already on one logical line and inactive #ifdef blocks (the PS3
# -only ISteamUser methods, for instance) are already gone. Parsing the raw headers instead
# silently produced both an abstract class -- multi-line declarations were missed -- and
# overrides of methods that do not exist in this configuration.
PURE = re.compile(r"virtual\s+(?P<ret>[^()]+?)\s*(?P<name>\w+)\s*\((?P<args>[^()]*)\)\s*(?:const\s*)?=\s*0\s*;")


def default_return(ret):
    """A safe default for a stubbed return type."""
    r = ret.strip()
    if r == "void":
        return ""
    if r.endswith("*"):
        return " return nullptr;"
    if r in ("bool",):
        return " return false;"
    # Covers int/uint32/uint64/float/enums/handles and by-value structs such as CSteamID.
    return " return {};"


def preprocess():
    """Run the real preprocessor over the Steamworks headers, in the engine's configuration.

    Using cpp rather than reading the headers directly is what makes the vtable correct:
    #ifdef-inactive methods must not be stubbed, and multi-line declarations must not be
    missed. Either mistake produces a class that compiles wrong or not at all.
    """
    src = "\n".join("#include \"%s\"" % h for h in
                    ["isteamgameserver.h", "isteamuser.h", "isteamapps.h", "isteamfriends.h"])
    cmd = ["g++", "-x", "c++", "-std=gnu++14", "-E", "-P",
           "-I", STEAM_DIR,
           "-I", os.path.join(REPO, "rehlds", "public"),
           "-I", os.path.join(REPO, "rehlds", "common"),
           "-"]
    p = subprocess.run(cmd, input=src, capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit("error: preprocessing failed:\n" + p.stderr[:2000])
    # Collapse to one line so multi-line declarations match as a unit.
    return re.sub(r"\s+", " ", p.stdout)


def parse(blob, classname):
    """Extract the pure virtuals of `classname` from preprocessed output."""
    m = re.search(r"class\s+" + classname + r"\s*\{(?P<body>.*?)\}\s*;", blob)
    if not m:
        sys.exit("error: interface %s not found in preprocessed output" % classname)

    methods = [(g.group("ret").strip(), g.group("name"), g.group("args").strip())
               for g in PURE.finditer(m.group("body"))]
    if not methods:
        sys.exit("error: no pure virtuals found for %s" % classname)
    return methods


def main():
    blob = preprocess()
    out = []
    w = out.append

    w("/*")
    w("* GENERATED by docs/audit/tools/gen_steam_stub.py -- do not edit by hand.")
    w("*")
    w("* Link-time Steamworks stub for 64-bit development builds.")
    w("*")
    w("* The bundled libsteam_api.so is 32-bit only. The 64-bit one from a modern Steam client")
    w("* implements SteamGameServer015 while these headers are pinned to SteamGameServer011")
    w("* (public/steam/isteamgameserver.h:258), so its vtable does not match and using it would")
    w("* corrupt silently rather than fail to link.")
    w("*")
    w("* This stub lets a 64-bit engine link and run in -insecure / LAN mode for portability")
    w("* work. It provides NO authentication, NO VAC and NO master-server listing. It must")
    w("* never be shipped. See docs/audit/16-steam-64bit.md.")
    w("*/")
    w("")
    w("#include \"precompiled.h\"")
    w("")
    w("namespace")
    w("{")

    accessors = []
    for classname in INTERFACES:
        methods = parse(blob, classname)
        stub = "C" + classname + "Stub"
        w("")
        w("// %s -- %d methods" % (classname, len(methods)))
        w("class %s : public %s" % (stub, classname))
        w("{")
        w("public:")
        for ret, name, args in methods:
            w("\tvirtual %s %s(%s) override {%s }" % (ret, name, args, default_return(ret)))
        w("};")
        w("")
        w("%s g_%s;" % (stub, stub))
        accessors.append((classname, stub))

    w("")
    w("} // namespace")
    w("")
    w("// --- exported accessors the engine links against ---------------------------------")
    w("")
    for classname, stub in accessors:
        # SteamGameServer() / SteamUser() / SteamApps() / SteamFriends()
        fn = classname[6:] if classname.startswith("ISteam") else classname
        w("S_API %s *Steam%s() { return &g_%s; }" % (classname, fn, stub))

    w("")
    w("S_API bool SteamAPI_Init() { return true; }")
    w("S_API bool SteamGameServer_Init(uint32, uint16, uint16, uint16, EServerMode, const char *)")
    w("{")
    w("\t// Must return true: sv_steam3.cpp:300-301 calls Sys_Error(\"Unable to initialize")
    w("\t// Steam.\") on failure, so returning false aborts startup instead of degrading.")
    w("\tCon_Printf(\"WARNING: Steam stub active -- no authentication, no VAC, no master server.\\n\");")
    w("\tCon_Printf(\"         64-bit development build only. Use -insecure.\\n\");")
    w("\treturn true;")
    w("}")
    w("S_API void SteamGameServer_Shutdown() {}")
    w("S_API void SteamGameServer_RunCallbacks() {}")
    w("S_API void SteamAPI_Shutdown() {}")
    w("S_API void SteamAPI_RunCallbacks() {}")
    w("S_API void SteamAPI_RegisterCallback(class CCallbackBase *, int) {}")
    w("S_API void SteamAPI_UnregisterCallback(class CCallbackBase *) {}")
    w("S_API void SteamAPI_UnregisterCallResult(class CCallbackBase *, SteamAPICall_t) {}")
    w("S_API void SteamAPI_SetBreakpadAppID(uint32) {}")
    w("S_API void SteamAPI_UseBreakpadCrashHandler(char const *, char const *, char const *, bool, void *, PFNPreMinidumpCallback) {}")
    w("")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
