/*
* GENERATED by docs/audit/tools/gen_steam_stub.py -- do not edit by hand.
*
* Link-time Steamworks stub for 64-bit development builds.
*
* The bundled libsteam_api.so is 32-bit only. The 64-bit one from a modern Steam client
* implements SteamGameServer015 while these headers are pinned to SteamGameServer011
* (public/steam/isteamgameserver.h:258), so its vtable does not match and using it would
* corrupt silently rather than fail to link.
*
* This stub lets a 64-bit engine link and run in -insecure / LAN mode for portability
* work. It provides NO authentication, NO VAC and NO master-server listing. It must
* never be shipped. See docs/audit/16-steam-64bit.md.
*/

#include "precompiled.h"

namespace
{

// ISteamGameServer -- 44 methods
class CISteamGameServerStub : public ISteamGameServer
{
public:
	virtual bool InitGameServer(uint32 unIP, uint16 usGamePort, uint16 usQueryPort, uint32 unFlags, AppId_t nGameAppId, const char *pchVersionString) override { return false; }
	virtual void SetProduct(const char *pszProduct) override { }
	virtual void SetGameDescription(const char *pszGameDescription) override { }
	virtual void SetModDir(const char *pszModDir) override { }
	virtual void SetDedicatedServer(bool bDedicated) override { }
	virtual void LogOn(const char *pszAccountName, const char *pszPassword) override { }
	virtual void LogOnAnonymous() override { }
	virtual void LogOff() override { }
	virtual bool BLoggedOn() override { return false; }
	virtual bool BSecure() override { return false; }
	virtual CSteamID GetSteamID() override { return {}; }
	virtual bool WasRestartRequested() override { return false; }
	virtual void SetMaxPlayerCount(int cPlayersMax) override { }
	virtual void SetBotPlayerCount(int cBotplayers) override { }
	virtual void SetServerName(const char *pszServerName) override { }
	virtual void SetMapName(const char *pszMapName) override { }
	virtual void SetPasswordProtected(bool bPasswordProtected) override { }
	virtual void SetSpectatorPort(uint16 unSpectatorPort) override { }
	virtual void SetSpectatorServerName(const char *pszSpectatorServerName) override { }
	virtual void ClearAllKeyValues() override { }
	virtual void SetKeyValue(const char *pKey, const char *pValue) override { }
	virtual void SetGameTags(const char *pchGameTags) override { }
	virtual void SetGameData(const char *pchGameData) override { }
	virtual void SetRegion(const char *pszRegion) override { }
	virtual bool SendUserConnectAndAuthenticate(uint32 unIPClient, const void *pvAuthBlob, uint32 cubAuthBlobSize, CSteamID *pSteamIDUser) override { return false; }
	virtual CSteamID CreateUnauthenticatedUserConnection() override { return {}; }
	virtual void SendUserDisconnect(CSteamID steamIDUser) override { }
	virtual bool BUpdateUserData(CSteamID steamIDUser, const char *pchPlayerName, uint32 uScore) override { return false; }
	virtual HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override { return {}; }
	virtual EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override { return {}; }
	virtual void EndAuthSession(CSteamID steamID) override { }
	virtual void CancelAuthTicket(HAuthTicket hAuthTicket) override { }
	virtual EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override { return {}; }
	virtual bool RequestUserGroupStatus(CSteamID steamIDUser, CSteamID steamIDGroup) override { return false; }
	virtual void GetGameplayStats() override { }
	virtual SteamAPICall_t GetServerReputation() override { return {}; }
	virtual uint32 GetPublicIP() override { return {}; }
	virtual bool HandleIncomingPacket(const void *pData, int cbData, uint32 srcIP, uint16 srcPort) override { return false; }
	virtual int GetNextOutgoingPacket(void *pOut, int cbMaxOut, uint32 *pNetAdr, uint16 *pPort) override { return {}; }
	virtual void EnableHeartbeats(bool bActive) override { }
	virtual void SetHeartbeatInterval(int iHeartbeatInterval) override { }
	virtual void ForceHeartbeat() override { }
	virtual SteamAPICall_t AssociateWithClan(CSteamID steamIDClan) override { return {}; }
	virtual SteamAPICall_t ComputeNewPlayerCompatibility(CSteamID steamIDNewPlayer) override { return {}; }
};

CISteamGameServerStub g_CISteamGameServerStub;

// ISteamUser -- 22 methods
class CISteamUserStub : public ISteamUser
{
public:
	virtual HSteamUser GetHSteamUser() override { return {}; }
	virtual bool BLoggedOn() override { return false; }
	virtual CSteamID GetSteamID() override { return {}; }
	virtual int InitiateGameConnection(void *pAuthBlob, int cbMaxAuthBlob, CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer, bool bSecure) override { return {}; }
	virtual void TerminateGameConnection(uint32 unIPServer, uint16 usPortServer) override { }
	virtual void TrackAppUsageEvent(CGameID gameID, int eAppUsageEvent, const char *pchExtraInfo = "") override { }
	virtual bool GetUserDataFolder(char *pchBuffer, int cubBuffer) override { return false; }
	virtual void StartVoiceRecording() override { }
	virtual void StopVoiceRecording() override { }
	virtual EVoiceResult GetAvailableVoice(uint32 *pcbCompressed, uint32 *pcbUncompressed, uint32 nUncompressedVoiceDesiredSampleRate) override { return {}; }
	virtual EVoiceResult GetVoice(bool bWantCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, bool bWantUncompressed, void *pUncompressedDestBuffer, uint32 cbUncompressedDestBufferSize, uint32 *nUncompressBytesWritten, uint32 nUncompressedVoiceDesiredSampleRate) override { return {}; }
	virtual EVoiceResult DecompressVoice(const void *pCompressed, uint32 cbCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, uint32 nDesiredSampleRate) override { return {}; }
	virtual uint32 GetVoiceOptimalSampleRate() override { return {}; }
	virtual HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override { return {}; }
	virtual EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override { return {}; }
	virtual void EndAuthSession(CSteamID steamID) override { }
	virtual void CancelAuthTicket(HAuthTicket hAuthTicket) override { }
	virtual EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override { return {}; }
	virtual bool BIsBehindNAT() override { return false; }
	virtual void AdvertiseGame(CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer) override { }
	virtual SteamAPICall_t RequestEncryptedAppTicket(void *pDataToInclude, int cbDataToInclude) override { return {}; }
	virtual bool GetEncryptedAppTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override { return false; }
};

CISteamUserStub g_CISteamUserStub;

// ISteamApps -- 19 methods
class CISteamAppsStub : public ISteamApps
{
public:
	virtual bool BIsSubscribed() override { return false; }
	virtual bool BIsLowViolence() override { return false; }
	virtual bool BIsCybercafe() override { return false; }
	virtual bool BIsVACBanned() override { return false; }
	virtual const char * GetCurrentGameLanguage() override { return nullptr; }
	virtual const char * GetAvailableGameLanguages() override { return nullptr; }
	virtual bool BIsSubscribedApp(AppId_t appID) override { return false; }
	virtual bool BIsDlcInstalled(AppId_t appID) override { return false; }
	virtual uint32 GetEarliestPurchaseUnixTime(AppId_t nAppID) override { return {}; }
	virtual bool BIsSubscribedFromFreeWeekend() override { return false; }
	virtual int GetDLCCount() override { return {}; }
	virtual bool BGetDLCDataByIndex(int iDLC, AppId_t *pAppID, bool *pbAvailable, char *pchName, int cchNameBufferSize) override { return false; }
	virtual void InstallDLC(AppId_t nAppID) override { }
	virtual void UninstallDLC(AppId_t nAppID) override { }
	virtual void RequestAppProofOfPurchaseKey(AppId_t nAppID) override { }
	virtual bool GetCurrentBetaName(char *pchName, int cchNameBufferSize) override { return false; }
	virtual bool MarkContentCorrupt(bool bMissingFilesOnly) override { return false; }
	virtual uint32 GetInstalledDepots(DepotId_t *pvecDepots, uint32 cMaxDepots) override { return {}; }
	virtual uint32 GetAppInstallDir(AppId_t appID, char *pchFolder, uint32 cchFolderBufferSize) override { return {}; }
};

CISteamAppsStub g_CISteamAppsStub;

// ISteamFriends -- 63 methods
class CISteamFriendsStub : public ISteamFriends
{
public:
	virtual const char * GetPersonaName() override { return nullptr; }
	virtual SteamAPICall_t SetPersonaName(const char *pchPersonaName) override { return {}; }
	virtual EPersonaState GetPersonaState() override { return {}; }
	virtual int GetFriendCount(int iFriendFlags) override { return {}; }
	virtual CSteamID GetFriendByIndex(int iFriend, int iFriendFlags) override { return {}; }
	virtual EFriendRelationship GetFriendRelationship(CSteamID steamIDFriend) override { return {}; }
	virtual EPersonaState GetFriendPersonaState(CSteamID steamIDFriend) override { return {}; }
	virtual const char * GetFriendPersonaName(CSteamID steamIDFriend) override { return nullptr; }
	virtual bool GetFriendGamePlayed(CSteamID steamIDFriend, FriendGameInfo_t *pFriendGameInfo) override { return false; }
	virtual const char * GetFriendPersonaNameHistory(CSteamID steamIDFriend, int iPersonaName) override { return nullptr; }
	virtual bool HasFriend(CSteamID steamIDFriend, int iFriendFlags) override { return false; }
	virtual int GetClanCount() override { return {}; }
	virtual CSteamID GetClanByIndex(int iClan) override { return {}; }
	virtual const char * GetClanName(CSteamID steamIDClan) override { return nullptr; }
	virtual const char * GetClanTag(CSteamID steamIDClan) override { return nullptr; }
	virtual bool GetClanActivityCounts(CSteamID steamIDClan, int *pnOnline, int *pnInGame, int *pnChatting) override { return false; }
	virtual SteamAPICall_t DownloadClanActivityCounts(CSteamID *psteamIDClans, int cClansToRequest) override { return {}; }
	virtual int GetFriendCountFromSource(CSteamID steamIDSource) override { return {}; }
	virtual CSteamID GetFriendFromSourceByIndex(CSteamID steamIDSource, int iFriend) override { return {}; }
	virtual bool IsUserInSource(CSteamID steamIDUser, CSteamID steamIDSource) override { return false; }
	virtual void SetInGameVoiceSpeaking(CSteamID steamIDUser, bool bSpeaking) override { }
	virtual void ActivateGameOverlay(const char *pchDialog) override { }
	virtual void ActivateGameOverlayToUser(const char *pchDialog, CSteamID steamID) override { }
	virtual void ActivateGameOverlayToWebPage(const char *pchURL) override { }
	virtual void ActivateGameOverlayToStore(AppId_t nAppID, EOverlayToStoreFlag eFlag) override { }
	virtual void SetPlayedWith(CSteamID steamIDUserPlayedWith) override { }
	virtual void ActivateGameOverlayInviteDialog(CSteamID steamIDLobby) override { }
	virtual int GetSmallFriendAvatar(CSteamID steamIDFriend) override { return {}; }
	virtual int GetMediumFriendAvatar(CSteamID steamIDFriend) override { return {}; }
	virtual int GetLargeFriendAvatar(CSteamID steamIDFriend) override { return {}; }
	virtual bool RequestUserInformation(CSteamID steamIDUser, bool bRequireNameOnly) override { return false; }
	virtual SteamAPICall_t RequestClanOfficerList(CSteamID steamIDClan) override { return {}; }
	virtual CSteamID GetClanOwner(CSteamID steamIDClan) override { return {}; }
	virtual int GetClanOfficerCount(CSteamID steamIDClan) override { return {}; }
	virtual CSteamID GetClanOfficerByIndex(CSteamID steamIDClan, int iOfficer) override { return {}; }
	virtual uint32 GetUserRestrictions() override { return {}; }
	virtual bool SetRichPresence(const char *pchKey, const char *pchValue) override { return false; }
	virtual void ClearRichPresence() override { }
	virtual const char * GetFriendRichPresence(CSteamID steamIDFriend, const char *pchKey) override { return nullptr; }
	virtual int GetFriendRichPresenceKeyCount(CSteamID steamIDFriend) override { return {}; }
	virtual const char * GetFriendRichPresenceKeyByIndex(CSteamID steamIDFriend, int iKey) override { return nullptr; }
	virtual void RequestFriendRichPresence(CSteamID steamIDFriend) override { }
	virtual bool InviteUserToGame(CSteamID steamIDFriend, const char *pchConnectString) override { return false; }
	virtual int GetCoplayFriendCount() override { return {}; }
	virtual CSteamID GetCoplayFriend(int iCoplayFriend) override { return {}; }
	virtual int GetFriendCoplayTime(CSteamID steamIDFriend) override { return {}; }
	virtual AppId_t GetFriendCoplayGame(CSteamID steamIDFriend) override { return {}; }
	virtual SteamAPICall_t JoinClanChatRoom(CSteamID steamIDClan) override { return {}; }
	virtual bool LeaveClanChatRoom(CSteamID steamIDClan) override { return false; }
	virtual int GetClanChatMemberCount(CSteamID steamIDClan) override { return {}; }
	virtual CSteamID GetChatMemberByIndex(CSteamID steamIDClan, int iUser) override { return {}; }
	virtual bool SendClanChatMessage(CSteamID steamIDClanChat, const char *pchText) override { return false; }
	virtual int GetClanChatMessage(CSteamID steamIDClanChat, int iMessage, void *prgchText, int cchTextMax, EChatEntryType *, CSteamID *) override { return {}; }
	virtual bool IsClanChatAdmin(CSteamID steamIDClanChat, CSteamID steamIDUser) override { return false; }
	virtual bool IsClanChatWindowOpenInSteam(CSteamID steamIDClanChat) override { return false; }
	virtual bool OpenClanChatWindowInSteam(CSteamID steamIDClanChat) override { return false; }
	virtual bool CloseClanChatWindowInSteam(CSteamID steamIDClanChat) override { return false; }
	virtual bool SetListenForFriendsMessages(bool bInterceptEnabled) override { return false; }
	virtual bool ReplyToFriendMessage(CSteamID steamIDFriend, const char *pchMsgToSend) override { return false; }
	virtual int GetFriendMessage(CSteamID steamIDFriend, int iMessageID, void *pvData, int cubData, EChatEntryType *peChatEntryType) override { return {}; }
	virtual SteamAPICall_t GetFollowerCount(CSteamID steamID) override { return {}; }
	virtual SteamAPICall_t IsFollowing(CSteamID steamID) override { return {}; }
	virtual SteamAPICall_t EnumerateFollowingList(uint32 unStartIndex) override { return {}; }
};

CISteamFriendsStub g_CISteamFriendsStub;

} // namespace

// --- exported accessors the engine links against ---------------------------------

S_API ISteamGameServer *SteamGameServer() { return &g_CISteamGameServerStub; }
S_API ISteamUser *SteamUser() { return &g_CISteamUserStub; }
S_API ISteamApps *SteamApps() { return &g_CISteamAppsStub; }
S_API ISteamFriends *SteamFriends() { return &g_CISteamFriendsStub; }

S_API bool SteamAPI_Init() { return true; }
S_API bool SteamGameServer_Init(uint32, uint16, uint16, uint16, EServerMode, const char *)
{
	// Must return true: sv_steam3.cpp:300-301 calls Sys_Error("Unable to initialize
	// Steam.") on failure, so returning false aborts startup instead of degrading.
	Con_Printf("WARNING: Steam stub active -- no authentication, no VAC, no master server.\n");
	Con_Printf("         64-bit development build only. Use -insecure.\n");
	return true;
}
S_API void SteamGameServer_Shutdown() {}
S_API void SteamGameServer_RunCallbacks() {}
S_API void SteamAPI_Shutdown() {}
S_API void SteamAPI_RunCallbacks() {}
S_API void SteamAPI_RegisterCallback(class CCallbackBase *, int) {}
S_API void SteamAPI_UnregisterCallback(class CCallbackBase *) {}
S_API void SteamAPI_UnregisterCallResult(class CCallbackBase *, SteamAPICall_t) {}
S_API void SteamAPI_SetBreakpadAppID(uint32) {}
S_API void SteamAPI_UseBreakpadCrashHandler(char const *, char const *, char const *, bool, void *, PFNPreMinidumpCallback) {}

